### ISSUE TITLE
Page looks different

### ISSUE THREAD

**Issue by JohannesWiesner** [G0RELLA/gorella_base#11]
Hi! Thanks for setting this up! I created my own GitHub page by:

Use this template -> Create a new repository -> Deploy from branch (master, /root)

But my page looks different, a lot of stuff is missing:

https://johanneswiesner.github.io/workshop_cimh/

It seems that something is deprecated with the deployment of `book.yml`

https://github.com/JohannesWiesner/workshop_cimh/actions/runs/4480037540/jobs/7874792015

> RuntimeError: 
> ===============================================================================
> 
> The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
> You may need to migrate from the old format, using:
> 
> 	jupyter-book toc migrate /home/runner/work/workshop_cimh/workshop_cimh/lecture/_toc.yml -o /home/runner/work/workshop_cimh/workshop_cimh/lecture/_toc.yml

**Comment by JohannesWiesner** [comment]
I think the format of `_toc.yml` has [changed](https://jupyterbook.org/en/stable/structure/toc.html#structure-the-table-of-contents)? I changed it to:

https://github.com/JohannesWiesner/workshop_cimh/blob/master/lecture/_toc.yml

**Comment by PeerHerholz** [comment]
Thx @JohannesWiesner for bringing this up. Unfortunately, most of us couldn't contribute to this project for a good while, including updates and new features/more content. We appreciate you checking out the current material and will address this asap.

Thanks again.

Cheers, Peer

N.B.: a new project kinda took over and might be, ie most definitely is, more up to date. You can find it [here](https://github.com/DiLER-Digitell).

**Comment by JohannesWiesner** [comment]
@PeerHerholz 

> N.B.: a new project kinda took over and might be, ie most definitely is, more up to date. You can find it [here](https://github.com/DiLER-Digitell).

Perfect, that's exactly what I was looking for!
